### ISSUE TITLE
bin demo

### ISSUE THREAD

**Issue by liliaoyuan** [kreelsama/InspectorTraceHandler#1]
Hi there!
The section part with trs to npy works well!
However I have tried to transfer bin to trs, I think it is the trs coding package. the data can not be extractored.
My trainset is here [panda2018](https://github.com/kistoday/Panda2018)
Is there any demo for a simple trace bin file ?

**Comment by ukouji** [comment]
Hello, 
The script only supports prasing traces collected from Inspector app. I don't know what is a '.bin' format is, it's not documented anywhere.
Also the code is no longer maintained due to I'm no longer actively working in this area.
Good luck going ahead.

**Comment by ukouji** [comment]
Hello,
```python
import os, sys
sys.path.append("/Users/kreel/Daily/")

from TraceHandler import TraceHandler

filename = '0022583f5f36ecb0cfaf8ae560397506_dc7edb1b00861183814ce24cb4bf6a32.bin'

fsize = os.stat(filename).st_size

handler = TraceHandler(with_header=False)

handler.append_file(filename)

print(fsize)
handler.set_attribute(NS=fsize, SC='byte')

handler.save2trs('s1.trs')
```
take this demo, use `SC='byte'`
